### PR TITLE
🐛 Fix instacam problems

### LINKED ISSUE #325: 🐛 Intermittent qr code error
Error is sometimes displayed after scanning QR code....

screen shot 2018-04-02 at 1 39 22 pm

### PR DESCRIPTION
**Pull request by astroash**
I'm not sure if this is the whole problem solved, but I can't replicate the error...

- Add ref to div rather than grabbing from DOM
- Comment out iife as I _think_ its duplicate code

Fixes #325

### CODE REVIEW

File: react-backend/client/src/components/visitors/qrcode.js [hunk 1]
```diff
@@ -93,6 +63,41 @@ export default class QRCode extends Component {
...
+        scanner
+          .stop()
+          .then(() => {
+            resolve(content);
+          })
+          .catch(() => {
+            reject('failure stopping scanner');
+          });
+      } else {
+        this.previewDiv.play();
```
Comment (eliascodes) [inline react-backend/client/src/components/visitors/qrcode.js]: If `previewDiv` is `null` we still try to call a method on it? This is what caused the original bug.

File: react-backend/client/src/components/visitors/qrcode.js [hunk 2]
```diff
@@ -93,6 +63,41 @@ export default class QRCode extends Component {
...
+
+    Instascan.Camera.getCameras()
+      .then((cameras) => {
+        if (cameras.length > 0) {
+          scanner.start(cameras[0]);
+        } else {
+          reject('ERROR HAPPENING AT getCameras');
+        }
+      })
+      .catch((err) => {
```
Comment (eliascodes) [inline react-backend/client/src/components/visitors/qrcode.js]: `catch(reject)`

**Comment by eliascodes** [comment]
Please use `rebase and merge` option from the drop-down when merging.

**Comment by eliascodes** [comment]
@astroash fix conflicts pls
