### PR TITLE
🚑 fix instascan critical error

### LINKED ISSUE #411: Reported: QR Scanning bug
Edward, via the google form:

> Samsung Galaxy Tab E

> I was trying to scan a QR code. It presented an error, which said "Register or new user" or "Try to Scan again", I chose scan again. The device would register no further QR code input until I restarted it. This is Edward 50% reporting this and 50% testing out this error reporter :)

### PR DESCRIPTION
**Pull request by eliascodes**
Fixes #411 

#### Changes
Instascan was repeatedly throwing errors "Uncaught abort() at Error".
Looks like this was due to not having proper clean-up code in the QRcode
component.

Added a `componentWillUnmount` hook to stop the scanner. Also moved the
scanning logic directly into `componentDidMount` instead of splitting it
between two methods, and renamed the `login` state fragment to a more
meaningful `hasScanned` boolean.

##### Fixing Bugs
* [ ] ~~Have I added a (set of) test(s) that proves the bug is fixed?~~ N/A
* [x] Have I documented any necessary developer notes/gotchas/lessons learnt from this bug fix?

### CODE REVIEW

File: client/src/visitors/pages/qrcode.js [hunk 1]
```diff
@@ -108,54 +124,14 @@ export default class QRCode extends Component {
       });
   }
 
-  componentWillUpdate(nextProps, nextState) {
-    if (nextState.username === 'there is no registered user') {
```
Comment (astroash) [inline client/src/visitors/pages/qrcode.js]: As we're no longer matching on this string, can this be removed from the route?

https://github.com/TwinePlatform/DataPower/blob/5dd8b49ab457c64245b50a7d5b54d6c70eb1ac88/server/routes/visitor_name.js#L18

Also in the above res it's sending the `hash: 0` property. Its also worth checking that the case this was previously solving, is also resolved in the rewrite.
