### PR TITLE
Visits data page

### LINKED ISSUE #334: Visits and Visitor woes
I think there's a bit of a mixup happening with the the Visitors and Visits pages. This is partly due to the fact things are mistitled in the designs. Below is my understanding of what things should be and what's wrong:

### Designs
This is correctly titled as **Visitor Details**. It should display a list of current users
screen shot 2018-04-05 at 1 12 47 pm

This is **incorrectly titled**. It should be called "Visits data", and display a list of visits with filterable graphs.
screen shot 2018-04-05 at 1 10 39 pm

### Our app
_note this is all taken from Eli's latest PR `visits-graphy-stuff`_

This page is correctly titled.
screen shot 2018-04-05 at 1 12 47 pm

This page is correctly titled, but has the incorrect info in the table below. The table seems to relate to individual visitors rather than a list of visits. 
screen shot 2018-04-05 at 1 19 04 pm
screen shot 2018-04-05 at 1 19 15 pm

### PR DESCRIPTION
**Pull request by eliascodes**
**MERGE #330 FIRST**

Final page on the CB admin side.

This is gross again, but we don't have time now, sorry.

fixes #334

### CODE REVIEW

File: react-backend/client/src/cb-admin/pages/VisitsData.js [hunk 1]
```diff
@@ -0,0 +1,338 @@
...
+    const today = now.format('dddd');
+    const lastWeek = now.subtract(7, 'days');
+
+    const dN = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
+    const dayName = circShift(dN, -dN.indexOf(today));
+
+    const initObj = dayName.reduce((acc, d) => { acc[d] = 0; return acc; }, {});
+    const visitCount = visits
+      .map(v => v.date)
+      .slice().sort()
```
Comment (astroash) [inline react-backend/client/src/cb-admin/pages/VisitsData.js]: What's the empty slice doing?

File: react-backend/client/src/cb-admin/pages/VisitsData.js [hunk 2]
```diff
@@ -0,0 +1,338 @@
...
+
+
+    return {
+      labels: dayName,
+      datasets: [
+        {
+          label: 'Visits over the last week',
+          data: dayName.map(n => visitCount[n]),
+          backgroundColor: [
+            colors.highlight_primary,
```
Comment (astroash) [inline react-backend/client/src/cb-admin/pages/VisitsData.js]: How come you're not using your `repeat` here?

File: react-backend/client/src/cb-admin/pages/VisitsData.js [hunk 3]
```diff
@@ -0,0 +1,338 @@
...
+      })
+      .catch(() => {
+        this.setState({ errors: { general: 'Unknown error' } });
+      });
+  }
+
+  render() {
+    const { errors } = this.state;
+    const activityOptions = [''].concat(this.state.activities).map((a, i) => ({ key: `${i}`, value: a }));
+    console.log(this.state.users);
```
Comment (astroash) [inline react-backend/client/src/cb-admin/pages/VisitsData.js]: 🔥

File: react-backend/client/src/cb-admin/pages/VisitsData.js (hunk 1 above)
Comment (eliascodes) [reply react-backend/client/src/cb-admin/pages/VisitsData.js]: cloning the array, because `sort` is mutative.

File: react-backend/client/src/cb-admin/pages/VisitsData.js [hunk 4]
```diff
@@ -0,0 +1,338 @@
...
+    return genderData;
+  };
+
+  getVisitsWeek = (visits) => {
+    const now = moment();
+    const today = now.format('dddd');
+    const lastWeek = now.subtract(7, 'days');
+
+    const dN = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
+    const dayName = circShift(dN, -dN.indexOf(today));
```
[the remark this answers is not in the document]
Comment (astroash) [reply react-backend/client/src/cb-admin/pages/VisitsData.js]: Lol, which bit are you okaying?

[the remark this answers is not in the document]
Comment (RogeredBacon) [reply react-backend/client/src/cb-admin/pages/VisitsData.js]: dayNames makes sense

**Comment by eliascodes** [comment]
@astroash 

screen shot 2018-04-05 at 18 44 13

Sonja asked for this table to also include the name of the visitor. I think you can drop "activities", and "date of visit", and instead include the email/phone number and or consent values.

It's also still making the request to `/api/visitors/all` which looks like it returns a list of visits, not a list of visitors (I think you want `/api/users/all` for that, but happy to be corrected by @RogeredBacon)

**Comment by eliascodes** [comment]
I think that's it though, once that's done and the conflicts are resolved, this can go in. Let me know if you want a hand.

**Comment by astroash** [comment]
@eliascodes I have only changed the table on the graphs page. I thought that's what we mentioned this morning. I can do the other page tomorrow.

**Comment by eliascodes** [comment]
Oh right ok, no problem 👍

**Comment by eliascodes** [comment]
@astroash fancy approving?

**Comment by eliascodes** [comment]
@RogeredBacon review please?
