### PR TITLE
Fix prop warnings

### LINKED ISSUE #216: 🐛Failed prop type errors on client console
screen shot 2018-02-25 at 15 13 15

Relates #202

### PR DESCRIPTION
**Pull request by eliascodes**
Fixes #216 

Watch out for the change to the database build file, I just changed some visit times, the tests should still pass, but I don't know if you're relying on them for anything in one of your branches!

Also a minor config change to play nice with the hotloading.

### CODE REVIEW

File: config/index.js [hunk 1]
```diff
@@ -43,23 +43,23 @@ const nodeEnvs = {
   dev: (cfg) =>
     mergeDeepRight(cfg, {
       env: 'dev',
-      web: { port: 3000 },
+      web: { port: 4000 },
```
Comment (astroash) [inline config/index.js]: Is this your favourite number?
